### PR TITLE
Adding CI/CD workflows

### LINKED ISSUE #18: Setup CI / CD
### Subject of the issue

CI / CD are not currently setup. The plan would be to remediate this via Github Actions.

### Expected behaviour

When a milestone is reached and the `develop` branch is merged into `master` we should run the CD process (build + deploy) automatically. Before a branch is merged into any other, we should first run the CI process (code style + tests). All of this should be acomplished via Github Actions and split into seperate configurations due to their nature.

The current plan is to use the following tools for the CI step:

- [Jest](https://jestjs.io/) for testing
- [Standard](https://standardjs.com/) for code formatting

The current plan is to use the following tools for the CD step:

- [TypeScript](https://www.typescriptlang.org/) for the build step
- [NPM CLI](https://docs.npmjs.com/cli-documentation/cli) for the release step

For both CI / CD, we will utilise [Github Actions](https://github.com/features/actions) as our runner.

### Actual behaviour

Currently we are manually checking code style, functionality, builds and releases. All of these areas should be automated so that developers can do what they do best... develop!

### Final notes

Comments and feedback welcome, new ideas or help appreciated also.

### PR DESCRIPTION
**Pull request by jamesrweb**
Should fix #18 and #13.

### CODE REVIEW

**Comment by jamesrweb** [comment]
The `npm-publish` script will run when you push a commit with a message to master using the format `Release v1.2.2` or `Release v2.2.3` for example. This script only runs on pushes to master.

The `format-code` script runs if the `format` script is present in the `package.json` and the `run-tests` script is the same, it needs the `test` script to exist in the `package.json` for it to be run. Both run on pull requests.

**Comment by egor-sorokin** [comment]
> The `npm-publish` script will run when you push a commit with a message to master using the format `Release 1.2.2` or `Release 2.2.3` for example. It will check that the version has changed from the last release and if it has, it will auto-deploy to npm for you. This script only runs on pushes to master.
> 
> The `format-code` script runs if the `format` script is present in the `package.json` and the `run-tests` script is the same, it needs the `test` script to exist in the `package.json` for it to be run. Both run on pull requests.

@jamesrweb probably it should be documented somewhere

**Comment by jamesrweb** [comment]
@egor-sorokin Good point, should I add it to the readme for now or did you have elsewhere in mind?

**Comment by egor-sorokin** [comment]
> @egor-sorokin Good point, should I add it to the readme for now or did you have elsewhere in mind?

yep, just add it in the readme

**Comment by jamesrweb** [comment]
@egor-sorokin Added into the readme now, please re-review the branch contents when you get the chance, thanks.

**Comment by jamesrweb** [comment]
Ah but @egor-sorokin  just be aware, I merged the other PR into this once (please read my proposal there to understand why before merging this one!)

**Comment by jamesrweb** [comment]
Merging this branch and closing #22 until [this issue and fixes outlined in PR #22](https://github.com/accessibility-tools/CI/pull/22#issuecomment-683994491) are resolved.

**Pull request merged**
